### PR TITLE
Validate image name

### PR DESCRIPTION
**Pull request by JohnPTobe**
This should address issue #13

### CODE REVIEW

**Comment by gisjedi** [comment]
On the whole this makes sense to me. I have a couple concerns though:

1. Do we need to define structs to unmarshal the JSON to extract PackageVersion? My main concern here is keeping the Go structs and the JSON schemas updated together. I'd prefer, if possible to maintain the schema in only one place. My Golang is very limited, but can't we just unmarshall into a generic interface{} as seen here: https://play.golang.org/p/gfP6P4SmaC I'm happy to hear an argument for why we should do it as presently implemented though.
2. We need to fix the unit tests as they are breaking in Travis presently. I'd also like to see a unit test covering the new `ValidImageName` function.

**Review by gisjedi — CHANGES_REQUESTED** [review]
Comments provided above.

**Comment by JohnPTobe** [comment]
I agree maintaining the structs and schema simultaneously could lead to maintenance issues.  It's probably easy enough to do this check without the structs but I had already made them for building seed json from user inputs with the seed creator program I've started so this was easy. I'll look into doing both without the structs and try to come up with some better options.  I also agree with updating the tests for this method.  I think the test images need to be updated as well to conform to the naming schema except for one with a bad name.

**Comment by gisjedi** [comment]
I don't have any problem using the structs presently, just want to make sure have other options if maintenance becomes problematic. Once you get the tests added and images corrected to match image naming, I'll be satisfied.

**Comment by JohnPTobe** [comment]
The travis build is working now but I'm not sure I like using relative paths  in my import  statement.

**Review by gisjedi — APPROVED** [review]

**Pull request merged**
