### PR TITLE
Initial implementation of validator

### PR DESCRIPTION
**Pull request by mattbanderson**
Initial implementation of validator executable in Go. Verifies that the JSON manifest in a specified Docker image label conforms to the Seed specification. Has some basic tests to check valid/invalid and associated error messages.

### CODE REVIEW

**Review by gisjedi — CHANGES_REQUESTED** [review]
Everything looks reasonable to me. 
2 things: 
- can we add unit test execution to travis build?
- squash commits down

**Comment by mattbanderson** [comment]
Sure, I will squash the commits.

The tests are definitely more integration tests than unit tests. I'll update the travis build on my fork and see if I can get the tests running successfully.

**Comment by mattbanderson** [comment]
OK, I verified the tests work in Travis on my fork and squashed the commits down to a single one. Let me know if you would like any other changes.

**Review by gisjedi — APPROVED** [review]
Something is out of wack with the rebase. I can come by and work through that with you this afternoon.

**Comment by mattbanderson** [comment]
I merged in the commits/history from ngageoint:master along with a single commit of the validator stuff. 

The build fails because the validator tests fail. The schema on ngageoint:master has invalid JSON (extra trailing comma on line 223). This is fixed in this pull request. So while the build does fail, the tests are doing their job by catching invalid JSON :)

**Pull request merged**
